version: '3.1'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8000:80"
    environment:
      - NGINX_BACKEND_SERVICE=http://app:8081

  app:
    build: .
    env_file:
      - .env.local
    environment:
      - SERVER_PORT=8081
      - DATA_DIR=/data
    volumes:
      - ./data/processed:/data
